spring.application.name=trade-journal

server.port=${SERVER_PORT_JOURNAL:1111}
server.servlet.context-path=/journal

spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=${JWT_SECRET}